#!/usr/bin/env bash
# Stage 6 — Normalize: produce a searchable/editorial layer from validated
# diplomatic YAML using the transcription-protocol normalization add-on.
#
# Input:  03_artifacts/*_transcription.yaml (diplomatic source of truth)
# Output: 05_normalized/*_normalized.yaml
#
# This does NOT modify the diplomatic YAML — normalization artifacts are
# derivatives stored in 05_normalized/ only.
#
# Usage:  s6_normalize.sh [--level mechanical|conservative_editorial|scholarly_editorial]
#                         [--provider anthropic|openai|gemini|ollama]
#                         [--prompt PATH_TO_NORM_PROMPT_YAML]
#                         [--dry-run]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.latin-ms"
[[ -f "$ENV_FILE" ]] && { set -a; source "$ENV_FILE"; set +a; }

NORM_LEVEL="${LATIN_MS_NORM_LEVEL:-conservative_editorial}"
PROVIDER="${TRANSCRIBER_SHELL_DEFAULT_PROVIDER:-anthropic}"
NORM_PROMPT=""
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --level)    NORM_LEVEL="$2"; shift 2 ;;
        --provider) PROVIDER="$2"; shift 2 ;;
        --prompt)   NORM_PROMPT="$2"; shift 2 ;;
        --dry-run)  DRY_RUN=true; shift ;;
        *) echo "Unknown: $1" >&2; exit 1 ;;
    esac
done

JOB_DIR="${LATIN_MS_WORKSPACE}/jobs/${LATIN_MS_JOB_ID}"
ARTIFACTS_DIR="${JOB_DIR}/03_artifacts"
NORM_DIR="${JOB_DIR}/05_normalized"
PROTOCOL_ROOT="${TRANSCRIBER_SHELL_PROTOCOL_ROOT:-${SCRIPT_DIR}/../../vendor/transcription-protocol}"
VALIDATE_SCRIPT="${PROTOCOL_ROOT}/benchmark/validate_normalization.py"

mkdir -p "$NORM_DIR"

echo "========================================================"
echo "  Stage 6: normalization  (level: ${NORM_LEVEL})"
echo "  Diplomatic source: ${ARTIFACTS_DIR}"
echo "  Output:            ${NORM_DIR}"
echo "  Provider:          ${PROVIDER}"
echo "========================================================"

# ── 1. Build norm_prompt.yaml if not supplied ─────────────────────────────────
if [[ -z "$NORM_PROMPT" ]]; then
    NORM_PROMPT="${JOB_DIR}/norm_prompt.yaml"
    if [[ ! -f "$NORM_PROMPT" ]]; then
        cat > "$NORM_PROMPT" <<YAML
# Auto-generated by s6_normalize.sh — edit as needed
protocolVersion: "1.1.0"
normalizationProtocolVersion: "norm-1.1.0"
editorialLevel: "${NORM_LEVEL}"
orthographyTarget: "classical"
abbreviationHandling: "expand"
lineBreakHandling: "reflow_to_spaces"
registerNotes: "medieval Latin, 14th-century English legal hand"
YAML
        echo "  Created norm_prompt.yaml at: $NORM_PROMPT"
    fi
fi

# ── 2. Run normalization per diplomatic YAML ──────────────────────────────────
# stage-4 writes 03_artifacts/<job_id>/<job_id>_transcription.yaml, so search
# recursively but skip *.tridis_era/ (Tridis-era backups) and any *.bak dirs.
# Use process substitution instead of mapfile (bash 3.2 on macOS lacks mapfile).
YAMLS=()
while IFS= read -r yaml_path; do
    YAMLS+=("$yaml_path")
done < <(find "$ARTIFACTS_DIR" \
    -type d \( -name '*.tridis_era' -o -name '*.bak' \) -prune -o \
    -type f -name '*_transcription.yaml' -print | sort)
if [[ ${#YAMLS[@]} -eq 0 ]]; then
    echo "  ERROR: no *_transcription.yaml found under $ARTIFACTS_DIR" >&2
    exit 1
fi

echo "  Processing ${#YAMLS[@]} diplomatic YAML(s)..."
echo ""

PASS=0; FAIL=0
for YAML_FILE in "${YAMLS[@]}"; do
    STEM=$(basename "$YAML_FILE" _transcription.yaml)
    OUT="${NORM_DIR}/${STEM}_normalized.yaml"

    if [[ -f "$OUT" ]]; then
        echo "  [skip] ${STEM} (already normalized)"
        PASS=$((PASS + 1))
        continue
    fi

    echo "  ==> ${STEM}"

    if [[ "$DRY_RUN" == "true" ]]; then
        # Write a minimal stub for pipeline smoke testing
        python3 - "$YAML_FILE" "$OUT" "$NORM_LEVEL" <<'PYEOF'
import sys, yaml, datetime
src, dst, level = sys.argv[1], sys.argv[2], sys.argv[3]
data = yaml.safe_load(open(src))
root = data.get("transcriptionOutput", data)
segs = root.get("segments", [])
norm_segs = [
    {"segmentId": s.get("segmentId", i+1),
     "diplomaticText": s.get("text", ""),
     "normalizedText": s.get("text", ""),
     "alignmentNotes": None,
     "changes": []}
    for i, s in enumerate(segs)
]
out = {
    "normalizationOutput": {
        "normalizationProtocolVersion": "norm-1.1.0",
        "source": {"sourcePageId": root.get("metadata", {}).get("sourcePageId",""), "sourceProtocolVersion": "1.1.0"},
        "normalizationPolicy": {"editorialLevel": level, "orthographyTarget": "classical",
                                 "abbreviationHandling": "expand", "lineBreakHandling": "reflow_to_spaces",
                                 "registerNotes": "dry-run stub"},
        "metadata": {"modelId": "dry-run", "timestamp": datetime.datetime.utcnow().isoformat()+"Z", "notes": None},
        "normalizedSegments": norm_segs,
    }
}
yaml.dump(out, open(dst, "w"), allow_unicode=True, default_flow_style=False)
print(f"  [dry-run] wrote stub {dst}")
PYEOF
        PASS=$((PASS + 1))
        continue
    fi

    # Derive image path: look for same stem in 01_pages/
    IMG="${JOB_DIR}/01_pages/${STEM}.jpg"
    if [[ ! -f "$IMG" ]]; then
        # Try common suffixes
        for EXT in jpeg png; do
            [[ -f "${JOB_DIR}/01_pages/${STEM}.${EXT}" ]] && IMG="${JOB_DIR}/01_pages/${STEM}.${EXT}" && break
        done
    fi

    if [[ ! -f "$IMG" ]]; then
        echo "    WARNING: image not found for ${STEM}, skipping LLM call" >&2
        FAIL=$((FAIL + 1))
        continue
    fi

    if TRANSCRIBER_SHELL_ARTIFACTS_DIR="$NORM_DIR" transcriber-shell run \
            --job-id "${LATIN_MS_JOB_ID}-norm-${STEM}" \
            --image "$IMG" \
            --prompt "$NORM_PROMPT" \
            --provider "$PROVIDER" \
            --no-diplomatic \
            2>&1; then
        PASS=$((PASS + 1))
    else
        echo "    ERROR: normalization failed for ${STEM}" >&2
        FAIL=$((FAIL + 1))
    fi
done

echo ""
echo "  Normalization complete: ${PASS} passed / ${FAIL} failed"

# ── 3. Validate outputs ───────────────────────────────────────────────────────
NORM_YAMLS=( "$NORM_DIR"/*_normalized.yaml )
if [[ ${#NORM_YAMLS[@]} -gt 0 ]] && [[ -f "${NORM_YAMLS[0]}" ]]; then
    echo ""
    echo "  Validating norm outputs..."
    VFAIL=0
    for NY in "${NORM_YAMLS[@]}"; do
        if python3 "$VALIDATE_SCRIPT" "$NY" &>/dev/null; then
            echo "  [OK]   $(basename $NY)"
        else
            echo "  [FAIL] $(basename $NY)" >&2
            VFAIL=$((VFAIL + 1))
        fi
    done
    [[ $VFAIL -gt 0 ]] && echo "  ${VFAIL} normalized YAML(s) failed validation" >&2
fi

echo ""
echo "========================================================"
echo "  Stage 6 done.  Normalized artifacts: ${NORM_DIR}"
echo "========================================================"
